Temporary disable net-im/telegram-desktop due to
    /var/tmp/portage/media-libs/tg_owt-0_pre20250515-r2/work/tg_owt-232ec410502e773024e8d83cfae83a52203306c0/src/modules/video_capture/linux/pipewire_session.cc:122:10:
    error: ‘spa_pod_object_find_prop’ was not declared in this scope;
    did
    you mean ‘spa_pod_parser_object_find_prop’?